dist: trusty
sudo: false
language: go
go:
- 1.8
before_install:
- openssl aes-256-cbc -K $encrypted_9171df62ed44_key -iv $encrypted_9171df62ed44_iv
  -in id_travis.enc -out id_travis -d
- openssl aes-256-cbc -K $encrypted_3ce59779d3a2_key -iv $encrypted_3ce59779d3a2_iv
  -in translations/crowdin.yaml.enc -out translations/crowdin.yaml -d
#- sudo apt-get update -q
#- sudo apt-get install -y perl make tidy default-jre-headless
- git fetch --unshallow
addons:
 apt:
   packages:
     - perl
     - tidy
     - default-jre-headless
script:
- make travis
notifications:
  recipients:
  - jfesler@gigo.com
  email:
    on_success: always
    on_failure: always
  slack: falling-sky:nvBQ0mBie8CK2RfPMVc6Ylmj#github
